# Generated by Django 2.2.28 on 2022-07-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.PositiveIntegerField(verbose_name='id_user')),
                ('id_way', models.PositiveIntegerField(verbose_name='id_way')),
                ('value', models.PositiveSmallIntegerField(verbose_name='value')),
                ('is_deleted', models.BooleanField(verbose_name='is_deleted')),
            ],
        ),
        migrations.CreateModel(
            name='user_to_way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.PositiveIntegerField(verbose_name='id_user')),
                ('way', models.TextField(verbose_name='way')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='rating')),
                ('show', models.BooleanField(verbose_name='show')),
                ('is_deleted', models.BooleanField(verbose_name='is_deleted')),
            ],
        ),
        migrations.CreateModel(
            name='way_to_comm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.PositiveIntegerField(verbose_name='id_user')),
                ('id_way', models.PositiveIntegerField(verbose_name='id_way')),
                ('comment', models.TextField(verbose_name='comment')),
                ('is_deleted', models.BooleanField(verbose_name='is_deleted')),
            ],
        ),
    ]
