# Generated by Django 2.2.27 on 2022-07-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Way', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'rating', 'verbose_name_plural': 'rating'},
        ),
        migrations.AlterModelOptions(
            name='user_to_way',
            options={'verbose_name': 'user_to_way', 'verbose_name_plural': 'user_to_way'},
        ),
        migrations.AlterModelOptions(
            name='way_to_comm',
            options={'verbose_name': 'way_to_comm', 'verbose_name_plural': 'way_to_comm'},
        ),
    ]
