# Generated by Django 2.2.27 on 2022-07-11 07:29

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Way', '0002_auto_20220711_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_to_way',
            name='way',
            field=jsonfield.fields.JSONField(default=dict, verbose_name='way'),
        ),
    ]
