# Generated by Django 2.2.27 on 2022-07-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Way', '0005_auto_20220713_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='way',
            new_name='ways',
        ),
    ]
