# Generated by Django 2.2.27 on 2022-07-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Way', '0006_auto_20220713_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ways',
            options={'verbose_name': 'ways', 'verbose_name_plural': 'ways'},
        ),
        migrations.AddField(
            model_name='ways',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='name'),
        ),
    ]
