# Generated by Django 2.2.27 on 2022-07-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Way', '0008_pageplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageplace',
            name='content',
        ),
        migrations.AddField(
            model_name='pageplace',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='name'),
        ),
    ]
