# Generated by Django 2.2.27 on 2022-07-21 08:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Way', '0009_auto_20220721_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageplace',
            name='name',
        ),
        migrations.AddField(
            model_name='pageplace',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
