# Generated by Django 2.2.27 on 2022-07-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Way', '0010_auto_20220721_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagePlace',
        ),
    ]
