# Generated by Django 2.2.27 on 2022-07-31 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Way', '0011_delete_pageplace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_to_way',
        ),
        migrations.RemoveField(
            model_name='ways',
            name='rating',
        ),
        migrations.AlterField(
            model_name='rating',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id_way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Way.ways'),
        ),
        migrations.AlterField(
            model_name='way_to_comm',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='way_to_comm',
            name='id_way',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Way.ways'),
        ),
        migrations.AlterField(
            model_name='ways',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
