# Generated by Django 2.2.27 on 2022-08-01 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Way', '0012_auto_20220731_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way_to_comm',
            name='id_way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Way.ways'),
        ),
    ]
