# Generated by Django 2.2.27 on 2022-07-29 08:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagePlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.PositiveIntegerField(default=0, verbose_name='id_user')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('short_info', models.CharField(default='', max_length=200)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
            ],
            options={
                'verbose_name': 'page place',
                'verbose_name_plural': 'page place',
            },
        ),
    ]
