# Generated by Django 2.2.27 on 2022-07-29 09:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PagePlaces', '0002_auto_20220729_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageplaces',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
