# Generated by Django 2.2.27 on 2022-07-29 09:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PagePlaces', '0003_auto_20220729_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageplaces',
            name='content1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
