# Generated by Django 2.2.27 on 2022-07-29 17:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagePlaces', '0004_pageplaces_content1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageplaces',
            name='content1',
        ),
        migrations.AddField(
            model_name='pageplaces',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pageplaces',
            name='url',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pageplaces',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
