# Generated by Django 2.2.27 on 2022-07-31 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PagePlaces', '0005_auto_20220729_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageplaces',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
