# Generated by Django 2.2.27 on 2022-08-01 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PagePlaces', '0006_auto_20220731_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageplaces',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pageplaces',
            name='url',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
