# Generated by Django 2.2.27 on 2022-08-02 09:59

import PagePlaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagePlaces', '0007_auto_20220801_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageplaces',
            name='icon',
            field=models.FileField(null=True, upload_to=PagePlaces.models.icon_place),
        ),
        migrations.AddField(
            model_name='pageplaces',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='pageplaces',
            name='lng',
            field=models.DecimalField(decimal_places=16, max_digits=19, null=True),
        ),
    ]
