# Generated by Django 2.2.27 on 2022-08-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagePlaces', '0009_auto_20220802_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, null=True, upload_to='icons/')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
            },
        ),
        migrations.RemoveField(
            model_name='pageplaces',
            name='icon',
        ),
    ]
