# Generated by Django 2.2.27 on 2022-08-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PagePlaces', '0011_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageplaces',
            name='icon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PagePlaces.Icon'),
        ),
    ]
