# Generated by Django 2.2.27 on 2022-08-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PagePlaces', '0015_auto_20220809_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='id_pageplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PagePlaces.PagePlaces'),
            preserve_default=False,
        ),
    ]
