# Generated by Django 2.2.27 on 2022-09-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagePlaces', '0017_auto_20220904_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageplaces',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
