# Generated by Django 4.1.1 on 2022-09-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagePlaces', '0018_pageplaces_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageplaces',
            name='phone',
            field=models.CharField(default='', max_length=13),
        ),
    ]
