# Generated by Django 2.2.27 on 2022-07-25 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150, verbose_name='first_name')),
                ('phone', models.CharField(default='', max_length=13)),
                ('show_phone', models.BooleanField(default=False)),
                ('url_user', models.CharField(default='', max_length=30)),
                ('show_email', models.BooleanField(default=False)),
                ('about_user', models.CharField(default='', max_length=2000)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
