# Generated by Django 2.2.27 on 2022-07-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_user_info_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='first_name',
        ),
    ]
