# Generated by Django 2.2.27 on 2022-07-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_remove_user_info_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='image_profile',
            field=models.FileField(null=True, upload_to='media/picture/'),
        ),
    ]
