# Generated by Django 2.2.27 on 2022-07-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_user_info_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='image_profile',
            field=models.FileField(null=True, upload_to='picture/'),
        ),
    ]
