# Generated by Django 2.2.27 on 2022-07-29 09:33

import Portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_auto_20220729_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='image_profile',
            field=models.FileField(null=True, upload_to=Portfolio.models.user_path),
        ),
    ]
