# Generated by Django 2.2.27 on 2022-07-31 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_auto_20220729_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='url_user',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=30),
        ),
    ]
