# Generated by Django 2.2.27 on 2022-08-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_auto_20220731_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='url_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
